#!/usr/bin/env python3
"""
Test ChaosChain Protocol with Funded Wallet

This script tests the complete protocol workflow with a funded wallet.
It will execute real on-chain transactions.

Wallet: 0x2BF4e0A1bd69ede0b55054c24c85bF912aEf4836

Prerequisites:
- Wallet must be funded with testnet ETH
- Run on Ethereum Sepolia

Usage:
    python test_with_funded_wallet.py
"""

import os
import sys
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

console = Console()

# Test wallet (generated by test_current_functionality.py)
TEST_WALLET_ADDRESS = "0x2BF4e0A1bd69ede0b55054c24c85bF912aEf4836"

def test_create_studio():
    """Test 1: Create a Studio"""
    console.print("\n[bold cyan]Test 1: Create Studio[/bold cyan]")
    
    try:
        from chaoschain_sdk import ChaosChainAgentSDK, AgentRole, NetworkConfig
        
        # Initialize SDK
        sdk = ChaosChainAgentSDK(
            agent_name="test_worker",
            agent_domain="test.chaoschain.local",
            agent_role=AgentRole.WORKER,
            network=NetworkConfig.ETHEREUM_SEPOLIA
        )
        
        # Check balance
        balance = sdk.wallet_manager.get_wallet_balance('test_worker')
        console.print(f"  [dim]Wallet balance: {balance} ETH[/dim]")
        
        if balance == 0:
            console.print("  [red]✗[/red] Wallet not funded!")
            console.print(f"  [yellow]Please fund: {TEST_WALLET_ADDRESS}[/yellow]")
            return False, None
        
        # Finance LogicModule on Ethereum Sepolia
        finance_logic = "0xC2B686C4EBA34701d0cC7f250D05B3c62c7CF492"
        
        console.print(f"  [cyan]→[/cyan] Creating studio with FinanceLogic...")
        studio_address = sdk.create_studio(
            name="Test Finance Studio",
            logic_module_address=finance_logic
        )
        
        console.print(f"  [green]✓[/green] Studio created: {studio_address}")
        return True, studio_address
        
    except Exception as e:
        console.print(f"  [red]✗[/red] Failed: {e}")
        console.print_exception()
        return False, None

def test_register_agent(sdk, studio_address):
    """Test 2: Register agent with ERC-8004"""
    console.print("\n[bold cyan]Test 2: Register Agent (ERC-8004)[/bold cyan]")
    
    try:
        # Check if already registered
        agent_id = sdk.chaos_agent.get_agent_id()
        
        if agent_id:
            console.print(f"  [green]✓[/green] Agent already registered: {agent_id}")
            return True, agent_id
        
        # Register
        console.print("  [cyan]→[/cyan] Registering agent...")
        agent_id, tx_hash = sdk.chaos_agent.register_agent()
        
        console.print(f"  [green]✓[/green] Agent registered: {agent_id}")
        console.print(f"  [dim]TX: {tx_hash}[/dim]")
        return True, agent_id
        
    except Exception as e:
        console.print(f"  [red]✗[/red] Failed: {e}")
        console.print_exception()
        return False, None

def test_register_with_studio(sdk, studio_address, agent_id):
    """Test 3: Register agent with Studio"""
    console.print("\n[bold cyan]Test 3: Register with Studio[/bold cyan]")
    
    try:
        # Register with studio (role 1 = WORKER, with stake)
        console.print(f"  [cyan]→[/cyan] Registering with studio...")
        tx_hash = sdk.register_with_studio(
            studio_address=studio_address,
            agent_id=agent_id,
            role=1,  # WORKER (enum value in contract)
            stake_amount=None  # Use default 0.0001 ETH
        )
        
        console.print(f"  [green]✓[/green] Registered with studio")
        console.print(f"  [dim]TX: {tx_hash}[/dim]")
        return True
        
    except Exception as e:
        console.print(f"  [red]✗[/red] Failed: {e}")
        console.print_exception()
        return False

def test_submit_work(sdk, studio_address):
    """Test 4: Submit work"""
    console.print("\n[bold cyan]Test 4: Submit Work[/bold cyan]")
    
    try:
        # Create a simple data hash (in production, this would be EIP-712 DataHash)
        import hashlib
        data_hash = bytes.fromhex(hashlib.sha256(b"test_work_submission").hexdigest())
        thread_root = bytes.fromhex(hashlib.sha256(b"test_thread_root").hexdigest())
        evidence_root = bytes.fromhex(hashlib.sha256(b"test_evidence_root").hexdigest())
        
        console.print(f"  [cyan]→[/cyan] Submitting work...")
        tx_hash = sdk.submit_work(
            studio_address=studio_address,
            data_hash=data_hash,
            thread_root=thread_root,
            evidence_root=evidence_root
        )
        
        console.print(f"  [green]✓[/green] Work submitted")
        console.print(f"  [dim]TX: {tx_hash}[/dim]")
        return True, data_hash
        
    except Exception as e:
        console.print(f"  [red]✗[/red] Failed: {e}")
        console.print_exception()
        return False, None

def test_scoring(sdk, studio_address, data_hash):
    """Test 5: Commit and reveal score"""
    console.print("\n[bold cyan]Test 5: Commit & Reveal Score[/bold cyan]")
    
    try:
        import hashlib
        import secrets
        
        # Generate score vector (8 dimensions: 5 PoA + 3 Finance-specific)
        score_vector = [8, 7, 9, 8, 7, 9, 8, 7]  # Scores out of 10
        
        # Generate random salt
        salt = secrets.token_bytes(32)
        
        # Compute commitment
        from eth_abi import encode
        encoded = encode(['uint8[]', 'bytes32'], [score_vector, salt])
        commitment = bytes.fromhex(hashlib.sha3_256(encoded).hexdigest())
        
        # Commit
        console.print(f"  [cyan]→[/cyan] Committing score...")
        tx_hash = sdk.commit_score(
            studio_address=studio_address,
            epoch=1,
            data_hash=data_hash,
            score_commitment=commitment
        )
        console.print(f"  [green]✓[/green] Score committed")
        console.print(f"  [dim]TX: {tx_hash}[/dim]")
        
        # Reveal
        console.print(f"  [cyan]→[/cyan] Revealing score...")
        tx_hash = sdk.reveal_score(
            studio_address=studio_address,
            epoch=1,
            data_hash=data_hash,
            score_vector=score_vector,
            salt=salt
        )
        console.print(f"  [green]✓[/green] Score revealed")
        console.print(f"  [dim]TX: {tx_hash}[/dim]")
        
        return True
        
    except Exception as e:
        console.print(f"  [red]✗[/red] Failed: {e}")
        console.print_exception()
        return False

def test_epoch_closure(sdk, studio_address):
    """Test 6: Close epoch"""
    console.print("\n[bold cyan]Test 6: Close Epoch[/bold cyan]")
    
    try:
        console.print(f"  [cyan]→[/cyan] Closing epoch 1...")
        tx_hash = sdk.close_epoch(
            studio_address=studio_address,
            epoch=1
        )
        
        console.print(f"  [green]✓[/green] Epoch closed")
        console.print(f"  [dim]TX: {tx_hash}[/dim]")
        return True
        
    except Exception as e:
        console.print(f"  [red]✗[/red] Failed: {e}")
        console.print_exception()
        return False

def test_rewards(sdk, studio_address):
    """Test 7: Check and withdraw rewards"""
    console.print("\n[bold cyan]Test 7: Check & Withdraw Rewards[/bold cyan]")
    
    try:
        # Check pending rewards
        console.print(f"  [cyan]→[/cyan] Checking pending rewards...")
        pending = sdk.get_pending_rewards(studio_address)
        console.print(f"  [green]✓[/green] Pending rewards: {pending} wei")
        
        if pending > 0:
            # Withdraw
            console.print(f"  [cyan]→[/cyan] Withdrawing rewards...")
            tx_hash = sdk.withdraw_rewards(studio_address)
            console.print(f"  [green]✓[/green] Rewards withdrawn")
            console.print(f"  [dim]TX: {tx_hash}[/dim]")
        else:
            console.print(f"  [yellow]⚠[/yellow] No rewards to withdraw")
        
        return True
        
    except Exception as e:
        console.print(f"  [red]✗[/red] Failed: {e}")
        console.print_exception()
        return False

def test_reputation(sdk, agent_id):
    """Test 8: Query reputation"""
    console.print("\n[bold cyan]Test 8: Query Reputation[/bold cyan]")
    
    try:
        console.print(f"  [cyan]→[/cyan] Querying reputation for agent {agent_id}...")
        reputation = sdk.chaos_agent.get_reputation(agent_id)
        
        console.print(f"  [green]✓[/green] Reputation entries: {len(reputation)}")
        return True
        
    except Exception as e:
        console.print(f"  [red]✗[/red] Failed: {e}")
        console.print_exception()
        return False

def main():
    """Run all tests"""
    console.print(Panel.fit(
        "[bold cyan]ChaosChain Protocol - Funded Wallet Test[/bold cyan]\n\n"
        f"Wallet: {TEST_WALLET_ADDRESS}\n"
        "Network: Ethereum Sepolia\n\n"
        "[yellow]⚠ This will execute real on-chain transactions![/yellow]",
        title="🧪 Integration Test"
    ))
    
    results = {}
    studio_address = None
    agent_id = None
    data_hash = None
    
    # Test 1: Create Studio
    success, studio_address = test_create_studio()
    results["Create Studio"] = success
    if not success:
        console.print("\n[red]Cannot proceed without studio[/red]")
        print_summary(results)
        return
    
    # Initialize SDK for remaining tests
    from chaoschain_sdk import ChaosChainAgentSDK, AgentRole, NetworkConfig
    sdk = ChaosChainAgentSDK(
        agent_name="test_worker",
        agent_domain="test.chaoschain.local",
        agent_role=AgentRole.WORKER,
        network=NetworkConfig.ETHEREUM_SEPOLIA
    )
    
    # Test 2: Register Agent
    success, agent_id = test_register_agent(sdk, studio_address)
    results["Register Agent"] = success
    if not success:
        console.print("\n[red]Cannot proceed without agent registration[/red]")
        print_summary(results)
        return
    
    # Test 3: Register with Studio
    success = test_register_with_studio(sdk, studio_address, agent_id)
    results["Register with Studio"] = success
    if not success:
        console.print("\n[yellow]Continuing despite studio registration failure...[/yellow]")
    
    # Test 4: Submit Work
    success, data_hash = test_submit_work(sdk, studio_address)
    results["Submit Work"] = success
    if not success:
        console.print("\n[yellow]Continuing despite work submission failure...[/yellow]")
    
    # Test 5: Scoring
    if data_hash:
        success = test_scoring(sdk, studio_address, data_hash)
        results["Commit & Reveal Score"] = success
    
    # Test 6: Epoch Closure
    success = test_epoch_closure(sdk, studio_address)
    results["Close Epoch"] = success
    
    # Test 7: Rewards
    success = test_rewards(sdk, studio_address)
    results["Check & Withdraw Rewards"] = success
    
    # Test 8: Reputation
    success = test_reputation(sdk, agent_id)
    results["Query Reputation"] = success
    
    # Print summary
    print_summary(results)

def print_summary(results):
    """Print test summary"""
    console.print("\n" + "="*80)
    
    table = Table(title="Test Results", show_header=True, header_style="bold cyan")
    table.add_column("Test", style="cyan")
    table.add_column("Status", justify="center")
    
    for test_name, passed in results.items():
        status = "[green]✓ PASS[/green]" if passed else "[red]✗ FAIL[/red]"
        table.add_row(test_name, status)
    
    console.print(table)
    
    passed = sum(1 for r in results.values() if r)
    total = len(results)
    
    if passed == total:
        console.print(Panel.fit(
            f"[bold green]✅ ALL TESTS PASSED ({passed}/{total})[/bold green]\n\n"
            "The protocol is working end-to-end!",
            title="🎉 Success",
            border_style="green"
        ))
    else:
        console.print(Panel.fit(
            f"[bold yellow]⚠ SOME TESTS FAILED ({passed}/{total} passed)[/bold yellow]\n\n"
            "Check the errors above for details.",
            title="⚠ Partial Success",
            border_style="yellow"
        ))

if __name__ == "__main__":
    main()

