name: Publish ChaosChain SDK

on:
  push:
    tags:
      - 'sdk-v*'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'testpypi'
        type: choice
        options:
        - testpypi
        - pypi

permissions:
  contents: write  # Required for creating releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: |
        cd packages/sdk
        python -m build
    
    - name: Check package
      run: |
        cd packages/sdk
        python -m twine check dist/*
    
    - name: Upload to TestPyPI
      if: github.event.inputs.environment == 'testpypi' || startsWith(github.ref, 'refs/tags/sdk-v') && contains(github.ref, 'test')
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TESTPYPI_API_TOKEN }}
      run: |
        cd packages/sdk
        python -m twine upload --repository testpypi dist/*
    
    - name: Upload to PyPI
      if: github.event.inputs.environment == 'pypi' || (startsWith(github.ref, 'refs/tags/sdk-v') && !contains(github.ref, 'test'))
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        cd packages/sdk
        python -m twine upload dist/*
    
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/sdk-v')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ChaosChain SDK ${{ github.ref }}
        body: |
          ## ChaosChain SDK Release
          
          ### Installation
          ```bash
          pip install chaoschain-sdk
          ```
          
          ### What's Changed
          - See [CHANGELOG.md](packages/sdk/CHANGELOG.md) for details
          
        draft: false
        prerelease: false
